sudo: required

dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - 10.4
  
script:
# Server
  - cd server
  - npm install
  - npm build
# Client
  - cd ../client
  - npm install
  - npm run build
  - npm run lint
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run test
  - npm run e2e
